theme: jekyll-theme-minimal
title: Zuzanna Kocjan 

logo: https://github.com/ZKocjan/cotzyan.github.io/blob/main/profile.jpg
twitter_username: cotzyan

github:
  is_project_page: false

google_analytics:
