theme: jekyll-theme-minimal 
title: Zuzanna Kocjan  
description: >
  Astronomy PhD Candidate.<br>
  Pronouns: she/her.<br>
  Surname pronunciation: Cotzyan.

logo: https://zkocjan.github.io/cotzyan.github.io/profile.jpg 

twitter_username: cotzyan 

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap


github: 
  is_project_page: false 
  
google_analytics: 
