theme: jekyll-theme-minimal 
title: Zuzanna Kocjan  
description: >
  Astronomy PhD Candidate at University of Maryland. Pronouns: she/her.

logo: https://zkocjan.github.io/cotzyan.github.io/profile.jpg 

twitter_username: cotzyan 

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

github: 
  is_project_page: false 
  
google_analytics: 
